import type { Metadata } from "next";
import Root from "@/components/layouts/Root";
import type { ChildrenProps } from "@/interfaces";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildrenProps) {
  return <Root>{children}</Root>;
}
